name: CI + Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *"
    
# PERMISSÕES GLOBAIS
permissions:
  contents: write 

jobs:
  format:
    name: Prettier Auto Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      
      - name: Instalar dependências
        run: npm install prettier

      - name: Rodar Prettier
        run: npx prettier --write .

      - name: Commitar e fazer push de arquivos formatados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format with Prettier"
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          branch: ${{ github.head_ref || github.ref_name }}
          
  deploy:
    name: Deploy para a vercel
    runs-on: ubuntu-latest
    needs: format 
    steps:

      - uses: actions/checkout@v4

      - name: Deploy na vercel
        uses: amondnet/vercel-action@v20
        with: 
          # O erro está nesta linha. O valor lido aqui é nulo ou vazio.
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--yes'
          working-directory: ./
